[build]
  command = "npm run build"
  publish = "build"
[dev]
  command = "npm run server:prod"
  publish = "public"
[build.environment]
  NODE_ENV = "production"
  PORT = "3000"
  CI = "false"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
